import Head from 'next/head'

import { DarkProvider } from '@/context/DarkContext';

import Container from './container';

export default function Home() {

  return (
    <>
      <DarkProvider>
        <Head>
          <title>ChatGPT BOT</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Container />
        </main>
      </DarkProvider>
    </>
  )
}
